Repository GroupBy-Side-Project-GSP/GSP_Android, pull requests merged in 2022-03, with the labels that each got.

#2 🔀 :: (#1) project setting
  .gitignore
  app/.gitignore
  app/build.gradle.kts
  app/proguard-rules.pro
  app/src/androidTest/java/com/gsps/gsp_android/ExampleInstrumentedTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/gsps/gsp_android/MainActivity.kt
  app/src/main/java/com/gsps/gsp_android/SplashActivity.kt
  app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  app/src/test/java/com/gsps/gsp_android/ExampleUnitTest.kt
  build.gradle.kts
  buildSrc/build.gradle.kts
  buildSrc/src/main/kotlin/Dependency.kt
  buildSrc/src/main/kotlin/Versions.kt
  gradle.properties
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle.kts
Labels: 프로젝트 설정

#4 🔀 :: (#3) package structure
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/gsps/gsp_android/data/remote/.gitkeep
  app/src/main/java/com/gsps/gsp_android/data/repository/.gitkeep
  app/src/main/java/com/gsps/gsp_android/di/.gitkeep
  app/src/main/java/com/gsps/gsp_android/di/module/.gitkeep
  app/src/main/java/com/gsps/gsp_android/ui/.gitkeep
  app/src/main/java/com/gsps/gsp_android/ui/base/.gitkeep
  app/src/main/java/com/gsps/gsp_android/ui/main/MainActivity.kt
  app/src/main/java/com/gsps/gsp_android/ui/splash/.gitkeep
  app/src/main/java/com/gsps/gsp_android/ui/splash/SplashActivity.kt
  app/src/main/java/com/gsps/gsp_android/utils/.gitkeep
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_splash.xml
Labels: 프로젝트 설정

#6 🔀 :: (#5) setup base
  app/src/main/java/com/gsps/gsp_android/ui/base/.gitkeep
  app/src/main/java/com/gsps/gsp_android/ui/base/BaseActivity.kt
  app/src/main/java/com/gsps/gsp_android/ui/base/BaseFragment.kt
Labels: 프로젝트 설정

#21 🔀 :: 로그인 xml font bug fix
  app/src/main/res/layout/activity_sign_in.xml
Labels: 버그

#47 🔀 :: (#33) 회사 상세 페이지 xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/gsps/gsp_android/ui/main/MemberInformationActivity.kt
  app/src/main/res/drawable/rounded_corner_main_lignten.xml
  app/src/main/res/layout/activity_member_information.xml
Labels: 기능 추가

#46 🔀 :: (#45) 관심 분야 전체 리스트 Activity
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/gsps/gsp_android/ui/main/InterestsFullListAdapter.kt
  app/src/main/java/com/gsps/gsp_android/ui/main/InterestsFullListFragment.kt
  app/src/main/java/com/gsps/gsp_android/ui/main/InterestsListAdapter.kt
  app/src/main/java/com/gsps/gsp_android/ui/main/InterestsListModel.kt
  app/src/main/java/com/gsps/gsp_android/ui/main/InterestsMemberAdapter.kt
  app/src/main/java/com/gsps/gsp_android/ui/main/InterestsMemberModel.kt
  app/src/main/java/com/gsps/gsp_android/ui/main/MainPageFragment.kt
  app/src/main/java/com/gsps/gsp_android/ui/main/NewMemberFragment.kt
  app/src/main/java/com/gsps/gsp_android/ui/main/NewMemberModel.kt
  app/src/main/res/drawable/rounded_corner_4dp.xml
  app/src/main/res/drawable/rounded_corner_dark_gray_stroke.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_sign_in.xml
  app/src/main/res/layout/fragment_interests_full_list.xml
  app/src/main/res/layout/fragment_main_page.xml
  app/src/main/res/layout/fragment_new_member.xml
  app/src/main/res/layout/interests_full_list_item.xml
  app/src/main/res/layout/interests_list_item.xml
  app/src/main/res/layout/interests_member_item.xml
  app/src/main/res/values/strings.xml
Labels: 기능 추가

#42 🔀 :: (#29) 메인 페이지 Activity
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/gsps/gsp_android/ui/main/InterestsListAdapter.kt
  app/src/main/java/com/gsps/gsp_android/ui/main/InterestsListModel.kt
  app/src/main/java/com/gsps/gsp_android/ui/main/InterestsMemberAdapter.kt
  app/src/main/java/com/gsps/gsp_android/ui/main/InterestsMemberModel.kt
  app/src/main/java/com/gsps/gsp_android/ui/main/MainPageFragment.kt
  app/src/main/java/com/gsps/gsp_android/ui/main/NewMemberFragment.kt
  app/src/main/java/com/gsps/gsp_android/ui/main/NewMemberModel.kt
  app/src/main/res/drawable/rounded_corner_4dp.xml
  app/src/main/res/drawable/rounded_corner_dark_gray_stroke.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_sign_in.xml
  app/src/main/res/layout/fragment_main_page.xml
  app/src/main/res/layout/fragment_new_member.xml
  app/src/main/res/layout/interests_list_item.xml
  app/src/main/res/layout/interests_member_item.xml
  app/src/main/res/values/strings.xml
Labels: 기능 추가

#41 🔀 :: (#40) search activity
  app/src/main/java/com/gsps/gsp_android/ui/main/ClickSearchFragment.kt
  app/src/main/java/com/gsps/gsp_android/ui/main/SearchFragment.kt
  app/src/main/java/com/gsps/gsp_android/ui/main/SearchRecentRecordAdapter.kt
  app/src/main/java/com/gsps/gsp_android/ui/main/SearchRecentRecordModel.kt
  app/src/main/java/com/gsps/gsp_android/ui/main/SearchResultAdapter.kt
  app/src/main/java/com/gsps/gsp_android/ui/main/SearchResultFragment.kt
  app/src/main/java/com/gsps/gsp_android/ui/main/SearchResultModel.kt
  app/src/main/java/com/gsps/gsp_android/ui/main/SearchTextAdapter.kt
  app/src/main/java/com/gsps/gsp_android/ui/main/SearchTextModel.kt
  app/src/main/res/drawable/ic_click_search_back.xml
  app/src/main/res/drawable/ic_click_search_close.xml
  app/src/main/res/drawable/ic_click_search_recent_record_close.xml
  app/src/main/res/drawable/ic_search_btn.xml
  app/src/main/res/drawable/item_search_interest_checkbox_background.xml
  app/src/main/res/drawable/item_search_interest_textcolor.xml
  app/src/main/res/drawable/search_background.xml
  app/src/main/res/layout/fragment_click_search.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/fragment_search_result.xml
  app/src/main/res/layout/item_recent_record.xml
  app/src/main/res/layout/item_search_result.xml
  app/src/main/res/layout/item_search_text.xml
Labels: 기능 추가

#39 🔀 :: (#35) search xml
  app/src/main/java/com/gsps/gsp_android/ui/main/ClickSearchFragment.kt
  app/src/main/java/com/gsps/gsp_android/ui/main/SearchFragment.kt
  app/src/main/java/com/gsps/gsp_android/ui/main/SearchResultFragment.kt
  app/src/main/res/drawable/ic_click_search_back.xml
  app/src/main/res/drawable/ic_click_search_close.xml
  app/src/main/res/drawable/ic_click_search_recent_record_close.xml
  app/src/main/res/drawable/ic_search_btn.xml
  app/src/main/res/drawable/item_search_interest_checkbox_background.xml
  app/src/main/res/drawable/item_search_interest_textcolor.xml
  app/src/main/res/drawable/search_background.xml
  app/src/main/res/layout/fragment_click_search.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/fragment_search_result.xml
  app/src/main/res/layout/item_recent_record.xml
  app/src/main/res/layout/item_search_result.xml
  app/src/main/res/layout/item_search_text.xml
Labels: 기능 추가

#38 🔀 :: (#24) 즐겨찾기한 회사 xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/gsps/gsp_android/ui/main/MyOfficeActivity.kt
  app/src/main/java/com/gsps/gsp_android/ui/main/MyOfficeAdapter.kt
  app/src/main/java/com/gsps/gsp_android/ui/main/MyOfficeModel.kt
  app/src/main/res/drawable/ic_myoffice_back.xml
  app/src/main/res/layout/activity_my_office.xml
  app/src/main/res/layout/my_office_item.xml
Labels: 기능 추가

#37 🔀 :: (#26) 마이페이지의 관심분야 설정
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/gsps/gsp_android/ui/main/InterestSettingActivity.kt
  app/src/main/res/drawable/ic_interest_setting_back.xml
  app/src/main/res/drawable/ic_mypage_interest_setting_back.xml
  app/src/main/res/drawable/interest_setting_btn_style.xml
  app/src/main/res/drawable/item_interest_setting_checkbox_background.xml
  app/src/main/res/drawable/item_interest_setting_textcolor.xml
  app/src/main/res/layout/activity_interest_setting.xml
Labels: 기능 추가

#49 🔀 :: (#48) 회사 상세 페이지 Activity
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/gsps/gsp_android/ui/main/MemberInfoActivity.kt
  app/src/main/java/com/gsps/gsp_android/ui/main/MemberInfoModel.kt
  app/src/main/java/com/gsps/gsp_android/ui/main/MemberInformationActivity.kt
  app/src/main/res/layout/activity_member_info.xml
Labels: 기능 추가

#34 🔀 :: (#31) 공지사항 activity
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/gsps/gsp_android/ui/main/AnnouncementActivity.kt
  app/src/main/java/com/gsps/gsp_android/ui/main/AnnouncementAdapter.kt
  app/src/main/java/com/gsps/gsp_android/ui/main/AnnouncementModel.kt
  app/src/main/java/com/gsps/gsp_android/ui/main/SubAnnouncementActivity.kt
  app/src/main/res/drawable/ic_announcement_back.xml
  app/src/main/res/layout/activity_announcement.xml
  app/src/main/res/layout/activity_sub_announcement.xml
  app/src/main/res/layout/item_announcement.xml
Labels: 기능 추가

#32 🔀 :: (#27) 마이페이지 공지사항 xml
  app/src/main/java/com/gsps/gsp_android/ui/main/AnnouncementActivity.kt
  app/src/main/java/com/gsps/gsp_android/ui/main/SubAnnouncementActivity.kt
Labels: 기능 추가

#30 🔀 :: (#25) sign up xml, activity
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/gsps/gsp_android/ui/main/SignUpActivity.kt
  app/src/main/res/drawable/ic_sign_up_back.xml
  app/src/main/res/drawable/sign_up_certification_btn.xml
  app/src/main/res/drawable/sign_up_login_go_btn.xml
  app/src/main/res/drawable/sign_up_next_btn.xml
  app/src/main/res/layout/activity_sign_up.xml
  app/src/main/res/values/strings.xml
Labels: 기능 추가

#23 🔀 :: (#19) mypage xml
  app/src/main/java/com/gsps/gsp_android/ui/main/MyPageFragment.kt
  app/src/main/res/drawable/ic_mypage_edit.xml
  app/src/main/res/drawable/ic_mypage_mic.xml
  app/src/main/res/drawable/ic_mypage_settings.xml
  app/src/main/res/drawable/ic_mypage_settings2.xml
  app/src/main/res/drawable/ic_mypage_star.xml
  app/src/main/res/drawable/ic_mypasge_tune.xml
  app/src/main/res/drawable/my_page_interest.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/values/strings.xml
Labels: 기능 추가

#18 🔀 :: (#17) 로그인 페이지 binding 리팩토링
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/gsps/gsp_android/ui/main/SignInActivity.kt
  app/src/main/res/layout/activity_sign_in.xml
Labels: 리펙토링
